### ISSUE TITLE
Long Term Performance Stability Graph Empty

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#10]
I believe some info here is also mssing:

![image](https://cloud.githubusercontent.com/assets/13221472/21450353/da98debc-c8fe-11e6-8018-e44ed2651b20.png)

**Comment by earlephilhower** [comment]
This is probably related to issue 9, so that ZIP file will help out.  Again, probably a locale thing.

**Comment by earlephilhower** [comment]
Just pushed commit 7823214474add10f7b1801835b4ed4cb6f70aeba which I believe addresses this, which AFAICT was due to the "," decimal separator in (the only) calculated output in the CSV/ODS file.  Please re-open with full STDOUT/STDERR and a ZIP of the full directory if you catch it again.  Thx!
-EFP3
