### ISSUE TITLE
Question regarding Sequential and Random Read workloads

### ISSUE THREAD

**Issue by alanrao** [earlephilhower/ezfio#18]
The tests that execute the multi-threaded Sequential Read and Random Read tests use asymmetric workloads (1 thread, 256 queue depth i the former case and 16 threads and 16 queue depth in the later). Is there a reason for this asymmetry: 

testname = "Sustained Multi-Threaded Sequential Read Tests by Block Size"
    seqrand = "Seq"
    wmix=0
    threads=1
    runtime=shorttime
    iops_log=False
    iodepth=256
    AddTestBSShmoo()

    testname = "Sustained Multi-Threaded Random Read Tests by Block Size"
    seqrand = "Rand"
    wmix=0
    threads=16
    runtime=shorttime
    iops_log=False
    iodepth=16
    AddTestBSShmoo()

**Comment by earlephilhower** [comment]
Yes, it's due to the way FIO does sequential-type accesses.  Each thread runs a sequential access pattern, starting at offset 0.  So if you did, for example, QD=1, THR=256, RW=READSEQ you'd end up reading the first block 256 times, then the 2nd block 256 times, (+/- any timing issues w/threading).

The only way to make a real sane sequential pattern is 1 thread with N QD.  Then you'll send out up to N read requests of block N, N+1, N+2, ... in sequence.

For random, each thread will have a different pseudo-random sequence and all is fine with the world, so you can spread the work amongst multiple cores/threads w/o any concerns like this.

Any particular problem you're having with this kind of setup?

**Comment by alanrao** [comment]
Hi Earle,

Thanks for the prompt response. I was not aware that FIO would not maintain the sequential order of workload across threads. There is no specific problem with this setup. The asymmetric workload between the Sequential and Random Read tests (coupled with the use of “multi-threaded” term in the Sequential Read test description) caught my eye.

Thanks again,

Narayan

**Comment by earlephilhower** [comment]
Happy to help.  I'll close this issue unless there's something else.
