### ISSUE TITLE
Threadripper 2990WX and EzFIO

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#27]
Hi,

I have tested the 970 PRO with both i5 8400 and the 32 Core 2990WX.

Could you please take a look at the results and tell if everyting is OK?

2290WX:
[ezfio.zip](https://github.com/earlephilhower/ezfio/files/2280189/ezfio.zip)

8400:

[ezfio.zip](https://github.com/earlephilhower/ezfio/files/2280190/ezfio.zip)

Regards

**Comment by earlephilhower** [comment]
Wow, 32 cores.  Here I was thinking my desktop 2nd-hand Xeon with 16 was kicking butt (it is, but only 1/2 as much, I guess!).

Anyway, as usual, because I'm an employee of another SSD company I can't comment on the absolute numbers.

The INTC results looks pretty good.  Note the scale on the 4K random write: the up and down is on a very small scale so it's basically noise and flat across QD.

Same 4K write comment for AMD.

If I had to *guess* (and I don't do much Windows work any more) I'd say there's some threading problems at the OS level that the INTC isn't seeing.  The 4K random read dip @ 128/256 is IMO (again, not verified as I don't do Windows or Threadripper much) related to OS task switching among the cores not going so well.  I don't have anything to suggest to fix it, though, as it's likely OS related (128 or 256 threads, maybe context switching is heavier-weight in the HW or less optimized by MSFT on AMD?).  FWIW it looks like AMD is running below INTC on all points for random read.
