### ISSUE TITLE
WD Black SN750 Test

### ISSUE THREAD

**Issue by coolrecep** [earlephilhower/ezfio#43]
Hey there. Long time no see!

Just wanted to share my WD Black SN750 test.

[ezfio.zip](https://github.com/earlephilhower/ezfio/files/4793064/ezfio.zip)

Something about write values are not right. They look like 15K which does not seem normal to me.

**Comment by coolrecep** [comment]
Earle Hey! Any problem with 980 PRO test?

[ezfio.zip](https://github.com/earlephilhower/ezfio/files/5787670/ezfio.zip)

Shouldn't this one have some info?

![image](https://user-images.githubusercontent.com/13221472/104025572-e5c97080-51d5-11eb-9570-a690b77286cb.png)

**Comment by earlephilhower** [comment]
Your ODS sheet and the script are not in sync so all the latency #s are bogus.  I don't know where the extra column is coming from, but check the Tests tab and you'll see the read/write latency are shifted out by one.  IIRC you're in a locale with `,` as a decimal point, so that might have bit you in the run.

Assuming it was that, I'd just copy and paste the values in columns I,J to H,I and call it a day here.

OTW, looks like an OK run.  Good luck!
