### ISSUE TITLE
multithreaded test not multithreaded?

### ISSUE THREAD

**Issue by mvernimmen** [earlephilhower/ezfio#64]
ezfio.py:
```
    testname = "Sustained Multi-Threaded Sequential Read Tests by Block Size"
    seqrand = "Seq"
    wmix = 0
    threads = 1
    runtime = shorttime
    iops_log = False
    iodepth = 256
    AddTestBSShmoo()
```

ezfio.ps1:
```
    $testname = "Sustained Multi-Threaded Sequential Read Tests by Block Size"
    $seqrand = "Seq"; $wmix=0; $threads=1; $runtime=$shorttime; $iops_log="`$false"; $iodepth=256
    AddTestBSShmoo
```
How is 'threads=1' multithreaded?
In my opinion either the text needs to be updated to state 'single-threaded' or the amount of threads needs to be set to something higher than 1.

**Comment by earlephilhower** [comment]
This was by design about 10 years ago when this came out.  "Threads" in this instance is really "outstanding asynchronous IOs" because running 256 threads would essentially test the Linux kernel and XEONs of the day's power to swap context (i.e. overhead unrelated to IO) , not IO capabilities.

For historical reasons the test pattern (and name) can't change, but FWIW the nomenclature was not an issue for folks doing DB storage design back in the day.  Most really intensive IO apps even today use async IO because it's still much lower overhead and data apps have been architected to support it already.
